/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as mainAppMainLayoutImport } from './routes/(main-app)/_main-layout'
import { Route as mainAppMainLayoutIndexImport } from './routes/(main-app)/_main-layout/index'
import { Route as mainAppMainLayoutLoginImport } from './routes/(main-app)/_main-layout/login'
import { Route as mainAppMainLayoutCalculatorImport } from './routes/(main-app)/_main-layout/calculator'
import { Route as mainAppMainLayoutAboutImport } from './routes/(main-app)/_main-layout/about'
import { Route as mainAppMainLayoutPostsIndexSlugImport } from './routes/(main-app)/_main-layout/posts/_index.$slug'

// Create Virtual Routes

const mainAppImport = createFileRoute('/(main-app)')()

// Create/Update Routes

const mainAppRoute = mainAppImport.update({
  id: '/(main-app)',
  getParentRoute: () => rootRoute,
} as any)

const mainAppMainLayoutRoute = mainAppMainLayoutImport.update({
  id: '/_main-layout',
  getParentRoute: () => mainAppRoute,
} as any)

const mainAppMainLayoutIndexRoute = mainAppMainLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainAppMainLayoutRoute,
} as any)

const mainAppMainLayoutLoginRoute = mainAppMainLayoutLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => mainAppMainLayoutRoute,
} as any)

const mainAppMainLayoutCalculatorRoute =
  mainAppMainLayoutCalculatorImport.update({
    id: '/calculator',
    path: '/calculator',
    getParentRoute: () => mainAppMainLayoutRoute,
  } as any)

const mainAppMainLayoutAboutRoute = mainAppMainLayoutAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => mainAppMainLayoutRoute,
} as any)

const mainAppMainLayoutPostsIndexSlugRoute =
  mainAppMainLayoutPostsIndexSlugImport.update({
    id: '/posts/_index/$slug',
    path: '/posts/$slug',
    getParentRoute: () => mainAppMainLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main-app)': {
      id: '/(main-app)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainAppImport
      parentRoute: typeof rootRoute
    }
    '/(main-app)/_main-layout': {
      id: '/(main-app)/_main-layout'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainAppMainLayoutImport
      parentRoute: typeof mainAppRoute
    }
    '/(main-app)/_main-layout/about': {
      id: '/(main-app)/_main-layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof mainAppMainLayoutAboutImport
      parentRoute: typeof mainAppMainLayoutImport
    }
    '/(main-app)/_main-layout/calculator': {
      id: '/(main-app)/_main-layout/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof mainAppMainLayoutCalculatorImport
      parentRoute: typeof mainAppMainLayoutImport
    }
    '/(main-app)/_main-layout/login': {
      id: '/(main-app)/_main-layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof mainAppMainLayoutLoginImport
      parentRoute: typeof mainAppMainLayoutImport
    }
    '/(main-app)/_main-layout/': {
      id: '/(main-app)/_main-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainAppMainLayoutIndexImport
      parentRoute: typeof mainAppMainLayoutImport
    }
    '/(main-app)/_main-layout/posts/_index/$slug': {
      id: '/(main-app)/_main-layout/posts/_index/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof mainAppMainLayoutPostsIndexSlugImport
      parentRoute: typeof mainAppMainLayoutImport
    }
  }
}

// Create and export the route tree

interface mainAppMainLayoutRouteChildren {
  mainAppMainLayoutAboutRoute: typeof mainAppMainLayoutAboutRoute
  mainAppMainLayoutCalculatorRoute: typeof mainAppMainLayoutCalculatorRoute
  mainAppMainLayoutLoginRoute: typeof mainAppMainLayoutLoginRoute
  mainAppMainLayoutIndexRoute: typeof mainAppMainLayoutIndexRoute
  mainAppMainLayoutPostsIndexSlugRoute: typeof mainAppMainLayoutPostsIndexSlugRoute
}

const mainAppMainLayoutRouteChildren: mainAppMainLayoutRouteChildren = {
  mainAppMainLayoutAboutRoute: mainAppMainLayoutAboutRoute,
  mainAppMainLayoutCalculatorRoute: mainAppMainLayoutCalculatorRoute,
  mainAppMainLayoutLoginRoute: mainAppMainLayoutLoginRoute,
  mainAppMainLayoutIndexRoute: mainAppMainLayoutIndexRoute,
  mainAppMainLayoutPostsIndexSlugRoute: mainAppMainLayoutPostsIndexSlugRoute,
}

const mainAppMainLayoutRouteWithChildren =
  mainAppMainLayoutRoute._addFileChildren(mainAppMainLayoutRouteChildren)

interface mainAppRouteChildren {
  mainAppMainLayoutRoute: typeof mainAppMainLayoutRouteWithChildren
}

const mainAppRouteChildren: mainAppRouteChildren = {
  mainAppMainLayoutRoute: mainAppMainLayoutRouteWithChildren,
}

const mainAppRouteWithChildren =
  mainAppRoute._addFileChildren(mainAppRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof mainAppMainLayoutIndexRoute
  '/about': typeof mainAppMainLayoutAboutRoute
  '/calculator': typeof mainAppMainLayoutCalculatorRoute
  '/login': typeof mainAppMainLayoutLoginRoute
  '/posts/$slug': typeof mainAppMainLayoutPostsIndexSlugRoute
}

export interface FileRoutesByTo {
  '/about': typeof mainAppMainLayoutAboutRoute
  '/calculator': typeof mainAppMainLayoutCalculatorRoute
  '/login': typeof mainAppMainLayoutLoginRoute
  '/': typeof mainAppMainLayoutIndexRoute
  '/posts/$slug': typeof mainAppMainLayoutPostsIndexSlugRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(main-app)': typeof mainAppRouteWithChildren
  '/(main-app)/_main-layout': typeof mainAppMainLayoutRouteWithChildren
  '/(main-app)/_main-layout/about': typeof mainAppMainLayoutAboutRoute
  '/(main-app)/_main-layout/calculator': typeof mainAppMainLayoutCalculatorRoute
  '/(main-app)/_main-layout/login': typeof mainAppMainLayoutLoginRoute
  '/(main-app)/_main-layout/': typeof mainAppMainLayoutIndexRoute
  '/(main-app)/_main-layout/posts/_index/$slug': typeof mainAppMainLayoutPostsIndexSlugRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/calculator' | '/login' | '/posts/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/calculator' | '/login' | '/' | '/posts/$slug'
  id:
    | '__root__'
    | '/(main-app)'
    | '/(main-app)/_main-layout'
    | '/(main-app)/_main-layout/about'
    | '/(main-app)/_main-layout/calculator'
    | '/(main-app)/_main-layout/login'
    | '/(main-app)/_main-layout/'
    | '/(main-app)/_main-layout/posts/_index/$slug'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  mainAppRoute: typeof mainAppRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  mainAppRoute: mainAppRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(main-app)"
      ]
    },
    "/(main-app)": {
      "filePath": "(main-app)",
      "children": [
        "/(main-app)/_main-layout"
      ]
    },
    "/(main-app)/_main-layout": {
      "filePath": "(main-app)/_main-layout.tsx",
      "parent": "/(main-app)",
      "children": [
        "/(main-app)/_main-layout/about",
        "/(main-app)/_main-layout/calculator",
        "/(main-app)/_main-layout/login",
        "/(main-app)/_main-layout/",
        "/(main-app)/_main-layout/posts/_index/$slug"
      ]
    },
    "/(main-app)/_main-layout/about": {
      "filePath": "(main-app)/_main-layout/about.tsx",
      "parent": "/(main-app)/_main-layout"
    },
    "/(main-app)/_main-layout/calculator": {
      "filePath": "(main-app)/_main-layout/calculator.tsx",
      "parent": "/(main-app)/_main-layout"
    },
    "/(main-app)/_main-layout/login": {
      "filePath": "(main-app)/_main-layout/login.tsx",
      "parent": "/(main-app)/_main-layout"
    },
    "/(main-app)/_main-layout/": {
      "filePath": "(main-app)/_main-layout/index.tsx",
      "parent": "/(main-app)/_main-layout"
    },
    "/(main-app)/_main-layout/posts/_index/$slug": {
      "filePath": "(main-app)/_main-layout/posts/_index.$slug.tsx",
      "parent": "/(main-app)/_main-layout"
    }
  }
}
ROUTE_MANIFEST_END */
